export const titles: string[] = [
	'lead front-end developer at E.ON',
	'senior software engineer at Toptal',
	'founding member at Braintrust',
	'a TypeScript fanatic',
	'a CSS wizard',
	'a JavaScript tinkerer',
	'a minimalist',
	'an open source enthusiast',
	'a maker of things',
	'an a11y and UX advocate',
	'a front-end magician',
	'a bug fixer',
	'a senior web developer',
	'I am into data visualization',
	'an UI architect',
	'I am obsessed with quality',
	'a web standards fanatic',
	'a JavaScript master',
	'a NodeJS hacker',
	'a father',
	'a husband'
];
