export const titles: string[] = [
	'an open source enthusiast',
	'a JavaScript tinkerer',
	'a senior software engineer at Toptal',
	'a founding member at Braintrust',
	'a lead front-end developer at E.ON',
	'an a11y and UX advocate',
	'I am into data visualization',
	'an UI architect',
	'a TypeScript fanatic',
	'a minimalist',
	'I am obsessed with quality',
	'a front-end magician',
	'a maker of things',
	'a bug fixer',
	'a web standards fanatic',
	'a NodeJS hacker',
	'a senior web developer',
	'a JavaScript master',
	'a CSS wizard',
	'a father',
	'a husband'
];
