name: 'Insights & NPM Stats'

on:
    workflow_dispatch:
    schedule:
        - cron: '0 0/6 * * *'

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@44c2b7a8a4ea60a981eaca3cf939b5f4305c123b # v4
            - uses: actions/setup-node@v4
              with:
                  node-version: 18
            - name: Build
              run: |
                  yarn
                  yarn insights
                  yarn npm-stats
              env:
                  MONGODB_URI: ${{ secrets.MONGODB_URI }}
                  NODE_OPTIONS: '--max_old_space_size=8192'
                  GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
                  GITLAB_TOKEN: ${{ secrets.GITLAB_TOKEN }}
                  LAST_FM_API_KEY: ${{ secrets.LAST_FM_API_KEY }}
