name: Screenshots

on:
    schedule:
        - cron: '0 0 1 * *'

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Build
              run: |
                  yarn
                  yarn screenshots
              env:
                  CLOUDINARY_API_KEY: ${{ secrets.CLOUDINARY_API_KEY }}
                  CLOUDINARY_API_SECRET: ${{ secrets.CLOUDINARY_API_SECRET }}
                  CLOUDINARY_CLOUD_NAME: ${{ secrets.CLOUDINARY_CLOUD_NAME }}
