name: 'Screenshots & Music'

on:
    workflow_dispatch:
    schedule:
        - cron: '0 0 * * 0'

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@1d96c772d19495a3b5c517cd2bc0cb401ea0529f # v4
            - uses: actions/setup-node@v4
              with:
                  node-version: 18
            - name: Build
              run: |
                  yarn
                  yarn screenshots
                  yarn fetch-music
              env:
                  MONGODB_URI: ${{ secrets.MONGODB_URI }}
                  NODE_OPTIONS: '--max_old_space_size=8192'
                  CLOUDINARY_API_KEY: ${{ secrets.CLOUDINARY_API_KEY }}
                  CLOUDINARY_API_SECRET: ${{ secrets.CLOUDINARY_API_SECRET }}
                  CLOUDINARY_CLOUD_NAME: ${{ secrets.CLOUDINARY_CLOUD_NAME }}
